services:
  redis:
    container_name: redis-for-seaerxng
    image: redis:7.2.4-bookworm
    restart: unless-stopped
    command: redis-server --save "" --appendonly "no"
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - redis-cache:/data

  searxng:
    container_name: searxng-for-cats
    image: searxng-for-cats
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
     - "8888:8080"
    volumes:
      - ./searxng-data:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://searx.daddy.cat
      - REDIS_URL=redis://redis:6379/0
      - UWSGI_WORKERS=8
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"
volumes:
  redis-cache:
  searxng-data:
